title: AAEA Git + GitHub Workshop

collections:
  topics:
    output: true
    permalink: aaea-workshop/:collection/:name
    
defaults:
  - scope:
      path: ""
      type: topics
    values:
      layout: topics
